name: CI/CD Backend

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - frontend/**
    tags:
      - '*'

  pull_request:
    branches:
      - '*'
    paths-ignore:
      - frontend/**


jobs:
  Build_Backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: docker build -t backend ./backend


  Sonar:
   needs: Build_Backend
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - name: SonarCloud Scan
       uses: SonarSource/sonarcloud-github-action@master
       env:
         GITHUB_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  Backend_Push_Latest_Image:
    if: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') }}
    needs: Sonar
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: create image from repository
        run: docker build -t ghcr.io/flickit-platform-dev/flickit-platform:"${GITHUB_SHA:0:7}" ./backend
      - name: login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: flickit-platform-dev
          password: ${{ secrets.GH_PACKAGES_TOKEN }}
      - name: push image to GitHub Container Registry
        run: docker push ghcr.io/flickit-platform-dev/flickit-platform:"${GITHUB_SHA:0:7}"

  Backend_Deploy_Latest:
    needs: Backend_Push_Latest_Image
    container: hamravesh.hamdocker.ir/public/darkube-cli:v1.1
    runs-on: ubuntu-latest
    steps:
      - name: Run script
        run: darkube deploy --ref main --token ${DARKUBE_DEPLOY_TOKEN} --app-id ${DARKUBE_APP_ID}  --image-tag "${GITHUB_SHA:0:7}" --job-id "$GITHUB_RUN_ID" --stateless-app true
        env:
          DARKUBE_DEPLOY_TOKEN: ${{ secrets.DARKUBE_DEPLOY_TOKEN_BACKEND_STAGE }}
          DARKUBE_APP_ID: ${{ secrets.DARKUBE_APP_ID_BACKEND_STAGE }}    



  Backend_Push_Image:
    if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') }}
    needs: Sonar
    runs-on: ubuntu-latest
    outputs:
      TAG: ${{ steps.TAG.outputs.tag }}
    steps:
      - uses: actions/checkout@v2
      - name: Set output
        id: TAG
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - name: Check output
        env:
          RELEASE_VERSION: ${{ steps.TAG.outputs.tag }}
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.TAG.outputs.tag }}
      - name: login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: flickit-platform-dev
          password: ${{ secrets.GH_PACKAGES_TOKEN }}
      - uses: actions/checkout@v2
      - name: create image from repository
        run: docker build -t ghcr.io/flickit-platform-dev/flickit-platform:${{ steps.TAG.outputs.tag }} ./backend
      - name: push image to GitHub Container Registry
        run: docker push ghcr.io/flickit-platform-dev/flickit-platform:${{ steps.TAG.outputs.tag }}

  Backend_Deploy:
    needs: Backend_Push_Image
    container: hamravesh.hamdocker.ir/public/darkube-cli:v1.1
    runs-on: ubuntu-latest
    steps:
      - name: Run script
        run: darkube deploy --ref main --token ${DARKUBE_DEPLOY_TOKEN} --app-id ${DARKUBE_APP_ID}  --image-tag "${TAG}" --job-id "$GITHUB_RUN_ID" --stateless-app true
        env:
          DARKUBE_DEPLOY_TOKEN: ${{ secrets.DARKUBE_DEPLOY_TOKEN_BACKEND }}
          DARKUBE_APP_ID: ${{ secrets.DARKUBE_APP_ID_BACKEND }}
          TAG: ${{needs.Backend_Push_Image.outputs.TAG}}

  
