name: CI/CD

on:
  push:
    branches:
      - '*'
    paths:
      - frontend/**
    tags:
      - '*'

  pull_request:
    branches:
      - '*'
    paths:
      - frontend/**



jobs:
  Build_Frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: docker build -t frontend ./frontend
